name: "💡 Feature Request"
description: Suggest an idea
title: "feat: "
labels: ["💡 feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: In this situation, I want to be able to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application does this affect?
      options:
        - Query Editor
        - Visualizations
        - Auth/User Management
        - Settings
        - Contract Integration
        - Other
    validations:
      required: true